export const FETCH_EVENTS= 'FETCH_EVENTS';
export const FETCH_EVENT = 'FETCH_EVENT';
export const CREATE_EVENT = 'CREATE_EVENT';
export const CREATE_EVENT_START = 'CREATE_EVENT_START';
export const EDIT_EVENT= "EDIT_EVENT";
export const DELETE_EVENT= "DELETE_EVENT";
